name: main

run-name: ${{ github.actor }} is running pipeline on main

on:
  push:
    branches:
      - "main"

env:
  TEST_TAG: cypher4859/galaxy-computer-parts:test
  LATEST_TAG: cypher4859/galaxy-computer-parts:latest


jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.LATEST_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image
    steps:
      - name: WIP
        run: |
          echo "Working on deployment"